"""Add update_flag to expenses table

Revision ID: fdc3550379e6
Revises: 
Create Date: 2024-11-06 19:42:46.281838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc3550379e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_flag', sa.Boolean(), nullable=True))

    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.drop_column('update_flag')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('update_flag')

    # ### end Alembic commands ###
